version: '3.9'
services:
  api:
    build: ./api/code
    hostname: api
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENDPOINT=${API_ENDPOINT}
    command: python api.py runserver ${API_HOST}:${API_PORT}
    volumes:
      - ./api/code:/app
    ports:
      - ${API_PORT}:${API_PORT}
  consumer:
    build: ./consumer/code
    hostname: consumer
    environment:
      - CONSUMER_HOST=${CONSUMER_HOST}
      - CONSUMER_PORT=${CONSUMER_PORT}
      - API_ENDPOINT=${API_ENDPOINT}
    command: python consumer.py runserver ${CONSUMER_HOST}:${CONSUMER_PORT}
    volumes:
      - ./consumer/code:/app
    ports:
      - ${CONSUMER_PORT}:${CONSUMER_PORT}
