# create docker from latest version of postgres. As of 10/08/2022 12.12 is the latest version
FROM postgres:12.12
# set environment variables to for the database
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=pass
# create database called as web
ENV POSTGRES_DB=web 
EXPOSE 5432
